/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Character = string;
export interface Features {
  'pointsPlayer1' : Points,
  'pointsPlayer2' : Points,
  'gameField' : GameField,
  'gameId' : GameId,
  'charactersPlayer1' : Character,
  'charactersPlayer2' : Character,
  'pointsDiffPlayer1' : PointsDiff,
  'pointsDiffPlayer2' : PointsDiff,
}
export type GameField = Array<Character>;
export type GameId = bigint;
export type Points = bigint;
export type PointsDiff = bigint;
export interface _SERVICE {
  'updateGameState' : ActorMethod<[GameField, boolean], Features>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];